### ISSUE TITLE
redis 6.0 can not work

### ISSUE THREAD

**Issue by w3yyb** [EFTEC/CacheOne#2]
CacheOneProviderRedis.php

at:
      $conStatus = @$this->redis->pconnect($server, $port, $timeout, null, $retry, $readTimeout);

chang to :
            $conStatus = @$this->redis->pconnect($server, $port, $timeout);

then works!

**Comment by jorgecc** [comment]
It works with the pecl extension (dll).  I don't know if it is compatible with any other library.
